name: CI Pipeline with Local Host Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Lint the code
      - name: Lint Code
        run: npm run lint

      # Step 5: Run tests
      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-test  # Only runs after the build-and-test job completes successfully

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (repeat since each job runs in a separate environment)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies (ensure the staging environment has the necessary packages)
      - name: Install Dependencies
        run: npm install

      # Step 4: Deploy Application
      - name: Deploy Application
        run: |
          echo "Deploying application to staging..."
          # Add your deployment command here
          # Example: 
          # npm run deploy-staging
