name: Node.js Test and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment only happens if the test job succeeds
    if: success()  # Only runs if the previous job is successful

    steps:
      # Check out the code again
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js again
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies again
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Heroku login
      - name: Log in to Heroku
        uses: akshnz/heroku-cli-action@v1
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}  # Store Heroku API key in GitHub Secrets

      # Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/PA4-IT26210-GP12.git  # Replace with your Heroku app name
          git push heroku main  # Push code to Heroku
