name: Node.js Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set file permissions for executable files
      - name: Set executable permissions
        run: |
          chmod -R +x ./.github
          chmod +x ./node_modules/.bin/*

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run tests
      - name: Run tests
        run: npm test
