name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure compatibility with your dependencies

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Use legacy-peer-deps if needed

      - name: Set permissions for Husky
        run: chmod +x .husky/*  # Ensure Husky hooks have the right permissions

      - name: Run Jest tests
        run: npm test  # This will trigger `jest`
